[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 800
via_ir = true

[rpc_endpoints]
etherlink = "https://node.mainnet.etherlink.com"
etherlink_testnet = "https://node.shadownet.etherlink.com"

[etherscan]
etherlink = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.etherlink.com/api" }
